version: "3"
services: 
  backend: 
    build: ./backend
    ports: 
      - 8000:8000
    depends_on:
      - mongo
    environment:
     - MONGO_URI=mongodb://mongo/blogPlatform

  mongo: 
    image: mongo:latest
    ports:
     - 27017:27017